[features]
seeds = false
skip-lint = false


[programs.localnet]
ciphera_verifier = "C1pherAVerifier111111111111111111111111"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
build = "anchor build"
test = "anchor test"